// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TicketStatus string

const (
	TicketStatusPending   TicketStatus = "pending"
	TicketStatusDone      TicketStatus = "done"
	TicketStatusFailed    TicketStatus = "failed"
	TicketStatusCancelled TicketStatus = "cancelled"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus
	Valid        bool // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type Ticket struct {
	ID          uuid.UUID
	Status      string
	Runat       pgtype.Timestamptz
	Nice        int16
	Type        string
	Ctime       pgtype.Timestamptz
	Mtime       pgtype.Timestamptz
	Attempts    int32
	Payload     []byte
	ErrorReason []byte
}
